### ISSUE TITLE
Exception while updating

### ISSUE THREAD

**Issue by pierrei** [prezi/snakebasket#5]
I just tried to build a new virtual env for dynapps and got this;

```
Obtaining prezi-aws from git+git@github.com:prezi/aws.git#egg=prezi_aws (from -r /Users/mrpi/Workspace/dynapps/virtualenv/src/prezi-django-utils/requirements.txt (line 2))
  Updating ./virtualenv/src/prezi-aws clone
  Running setup.py egg_info for package prezi-aws

  Found requirements.txt in prezi-aws, installing extra dependencies.
Skipping installation of prezi-config from git+git@github.com:prezi/config.git#egg=prezi-config because a newer version has already been downloaded.
Requirement already satisfied (use --upgrade to upgrade): mock in ./virtualenv/lib/python2.7/site-packages (from -r /Users/mrpi/Workspace/dynapps/virtualenv/src/prezi-django-utils/requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): coverage==3.4 in ./virtualenv/lib/python2.7/site-packages (from -r /Users/mrpi/Workspace/dynapps/virtualenv/src/prezi-django-utils/requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): unittest-xml-reporting==1.3.2 in ./virtualenv/lib/python2.7/site-packages (from -r /Users/mrpi/Workspace/dynapps/virtualenv/src/prezi-django-utils/requirements.txt (line 10))
Exception:
Traceback (most recent call last):
  File "/Users/mrpi/Workspace/dynapps/virtualenv/src/pip/pip/basecommand.py", line 107, in main
    status = self.run(options, args)
  File "/Users/mrpi/Workspace/dynapps/virtualenv/src/snakebasket/snakebasket/commands/install.py", line 348, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/mrpi/Workspace/dynapps/virtualenv/src/snakebasket/snakebasket/commands/install.py", line 91, in prepare_files
    installed_version = self.install_req_checker.req_installed_version(req_to_install)
  File "/Users/mrpi/Workspace/dynapps/virtualenv/src/snakebasket/snakebasket/versions.py", line 216, in req_installed_version
    if self.is_install_req_newer(already_installed_req, install_req):
  File "/Users/mrpi/Workspace/dynapps/virtualenv/src/snakebasket/snakebasket/versions.py", line 227, in is_install_req_newer
    editable_reqs = [req for req in reqs_in_conflict if req.editable == True]
  File "/Users/mrpi/Workspace/dynapps/virtualenv/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 2292, in __getattr__
    return getattr(self._provider, attr)
AttributeError: PathMetadata instance has no attribute 'editable'

Storing complete log in /Users/mrpi/.config/pip/pip.log
```

**Comment by pierrei** [comment]
Apparently I was using an old version of snakebasket. Case closed.

**Comment by neumark** [comment]
Thank you for filing bugs!

On Tue, Jan 29, 2013 at 11:48 AM, Pierre Ingmansson <
notifications@github.com> wrote:

> Apparently I was using an old version of snakebasket. Case closed.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/prezi/snakebasket/issues/5#issuecomment-12829297.

## 

_Peter Neumark_
Developer at Prezi http://prezi.com
