### ISSUE TITLE
sb install doesn't work when running update_requirements.sh in dynapps

### ISSUE THREAD

**Issue by szilveszter** [prezi/snakebasket#6]
Here's the terminal session:

```
(virtualenv)szilveszter@madrid:~/Prezi/repo/dynapps$ ./update_requirements.sh 
Obtaining pip from git+http://github.com/pypa/pip.git@854574f65c4ef92da8dd78b9831a9604dcc9957a#egg=pip
  Updating ./virtualenv/src/pip clone (to 854574f65c4ef92da8dd78b9831a9604dcc9957a)
  Could not find a tag or branch '854574f65c4ef92da8dd78b9831a9604dcc9957a', assuming commit.
  Running setup.py egg_info for package pip

    warning: no files found matching '*.html' under directory 'docs'
    warning: no previously-included files matching '*.txt' found under directory 'docs/_build'
    no previously-included directories found matching 'docs/_build/_sources'
Obtaining snakebasket from git+git@github.com:prezi/snakebasket.git@c86911726193ead2a48b6e267fbe31d817931a3b#egg=snakebasket
  Updating ./virtualenv/src/snakebasket clone (to c86911726193ead2a48b6e267fbe31d817931a3b)
  Could not find a tag or branch 'c86911726193ead2a48b6e267fbe31d817931a3b', assuming commit.
  Running setup.py egg_info for package snakebasket

Installing collected packages: pip, snakebasket
  Running setup.py develop for pip

    warning: no files found matching '*.html' under directory 'docs'
    warning: no previously-included files matching '*.txt' found under directory 'docs/_build'
    no previously-included directories found matching 'docs/_build/_sources'
    Creating /Users/szilveszter/Prezi/repo/dynapps/virtualenv/lib/python2.7/site-packages/pip.egg-link (link to .)
    pip 1.2.1.post1 is already the active version in easy-install.pth
    Installing pip script to /Users/szilveszter/Prezi/repo/dynapps/virtualenv/bin
    Installing pip-2.7 script to /Users/szilveszter/Prezi/repo/dynapps/virtualenv/bin

    Installed /Users/szilveszter/Prezi/repo/dynapps/virtualenv/src/pip
  Running setup.py develop for snakebasket

    Creating /Users/szilveszter/Prezi/repo/dynapps/virtualenv/lib/python2.7/site-packages/snakebasket.egg-link (link to .)
    snakebasket 2.0.0 is already the active version in easy-install.pth
    Installing sb script to /Users/szilveszter/Prezi/repo/dynapps/virtualenv/bin

    Installed /Users/szilveszter/Prezi/repo/dynapps/virtualenv/src/snakebasket
Successfully installed pip snakebasket
Cleaning up...
Traceback (most recent call last):
  File "/Users/szilveszter/Prezi/repo/dynapps/virtualenv/bin/sb", line 9, in <module>
    load_entry_point('snakebasket==2.0.0', 'console_scripts', 'sb')()
  File "/Users/szilveszter/Prezi/repo/dynapps/virtualenv/src/snakebasket/snakebasket/main.py", line 5, in main
    install_pip_patches()
  File "/Users/szilveszter/Prezi/repo/dynapps/virtualenv/src/snakebasket/snakebasket/main.py", line 9, in install_pip_patches
    from snakebasket.commands import install
  File "/Users/szilveszter/Prezi/repo/dynapps/virtualenv/src/snakebasket/snakebasket/commands/install.py", line 3, in <module>
    from pip.req import InstallRequirement, InstallationError, _make_build_dir, parse_requirements, Requirements
ImportError: No module named req
(virtualenv)szilveszter@madrid:~/Prezi/repo/dynapps$ python
Python 2.7.2 (default, Jun 20 2012, 16:23:33) 
[GCC 4.2.1 Compatible Apple Clang 4.0 (tags/Apple/clang-418.0.60)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pip.req import InstallRequirement, InstallationError, _make_build_dir, parse_requirements, Requirements
>>> 
```

Any ideas what I'm doing wrong here?

**Comment by cassus** [comment]
same error here

**Comment by szilveszter** [comment]
I think the solution was to trash pip by hand from the virtualenv (removing the directory), and install it again

**Comment by cassus** [comment]
re-generating the virtualenv from scratch also helped
